# Generated by Django 2.2 on 2022-01-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220111_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='iid',
            field=models.IntegerField(default=1),
        ),
    ]
