# Generated by Django 2.2 on 2022-01-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_iid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='iid',
        ),
    ]
